### ISSUE TITLE
Can't compile because of unavailable dependency

### ISSUE THREAD

**Issue by ikennalunatech** [raboof/akka-http-backpressure#3] opened 2018-05-06 16:02 UTC
Hi,

The project fails to compile because this dependency `sbt-paradox-reveal-js` is not resolved.

Error
```
 coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     net.bzzt:paradox-theme-reveal-js:0.4:
```

**Comment by raboof** [comment] 2018-05-06 16:09
Thanks for the report! That dependency is hosted at https://bintray.com/raboofje/sbt-plugins/sbt-paradox-reveal-js, and that repo should have been made available via https://github.com/raboof/akka-http-backpressure/blob/master/project/plugins.sbt#L4 and https://github.com/raboof/paradox-theme-reveal.js/blob/master/plugin/src/main/scala/ParadoxRevealPlugin.scala#L13

That seemed to work for me. I see you're using coursier, I'm guessing you configured that in your ~/.sbt? Perhaps this approach does not work with coursier?

**Comment by raboof** [comment] 2018-05-17 19:36
I just removed paradox-theme-reveal-js from my ~/.ivy2 and added coursier as documented in https://github.com/coursier/coursier#sbt-plugin but it still seemed to work fine...

Closing this issue for now since I'm not sure how to reproduce the issue - feel free to reopen if you have a reproducer!

**Closed as completed by raboof** 2018-05-17 19:36 UTC

**Comment by idarlington** [comment] 2018-05-31 09:19
It is possible my sbt setup may be broken but adding this 
```
resolvers+= Resolver.bintrayRepo("raboofje", "maven")
```
 to `build.sbt` resolved it.

**Comment by raboof** [comment] 2018-05-31 09:53
weird, glad to hear you resolved it though!
